### PR TITLE
Fix link description (#23)

### PR DESCRIPTION
**Pull request by Rodrigue819**

### CODE REVIEW

**Comment by HarshKapadia2** [comment]
Thank you for the PR, @Rodrigue819!

Changes:
- There is a small typo in the `what_is_github.adoc` file. There is an extra `[`. Please make another commit to remove it.
image
- Please follow the instructions in the [`CONTRIBUTING.md`](https://github.com/HarshKapadia2/git_basics/blob/master/CONTRIBUTING.md) file to generate an `index.html` file. Please make another commit to include the file after the first point is covered.

**Comment by HarshKapadia2** [comment]
Hey @Rodrigue819 I was going through the files and found one link in `git_merge.adoc` that you missed. Could you please correct that, generate a new `index.html` and make a commit?

A picture for your ref (the 2nd line has the link that you missed):

image

**Comment by HarshKapadia2** [comment]
Also, you have not covered the second part of the issue:
> Remove hyperlinks on pictures.

Just remove the `link` attribute in the pictures (if present), generate `index.html` and make a commit.

The files `git_add.adoc`, `git_pull.adoc`, `git_merge.adoc` and `git_push.adoc` have pictures with the `link` attribute. (Just check other files as well, to be sure. I couldn't find any more.)

**Comment by Rodrigue819** [comment]
@HarshKapadia2 I've made the change for the missed link. I did another PR with the link in the picture. I originally missed that one and did not want to mess with the PR that you already had revised. Look at PR #48

**Comment by HarshKapadia2** [comment]
In the future, please remember to make a new branch for every PR. It is not a good practice to make PRs from the master branch. If you don't know how to do that, you can [learn to make a PR](https://harshkapadia2.github.io/git_basics/#_resources:~:text=Learn%20how%20to%20make%20a%20Pull%20Request%20(PR)).

**Comment by HarshKapadia2** [comment]
> I did another PR with the link in the picture. I originally missed that one and did not want to mess with the PR that you already had revised. Look at PR #48

Oh my bad. I'll have a look.

**Comment by HarshKapadia2** [comment]
The PRs for issue #23 are #46 and #49.

**Pull request merged**
