### PR TITLE
Add --allow-empty flag

### PR DESCRIPTION
**Pull request by MahmoudDawood**
- [x] Add _'Push Empty Git Commits'_

### CODE REVIEW

**Comment by HarshKapadia2** [comment]
Thank you for the PR @MahmoudDawood!

Some changes that I would request you to make
- Shift this option **below** the [`-a or --all` option](https://harshkapadia2.github.io/git_basics/#_a_or_all).
- Add a point that talks about what the `--allow-empty` option does and make that the first point.
	- Please keep the [language requirements](https://github.com/HarshKapadia2/git_basics/blob/main/CONTRIBUTING.md#language-code-and-syntax) in mind.
- The point on building a project without changes should be the 2nd point and can be framed as 'One usecase can be to trigger a CI/CD workflow without making changes to the project.'.
- The `git alias` point is not required.

**Comment by MahmoudDawood** [comment]
Thank you for the feedback @HarshKapadia2!

Was it done right this time?

**Comment by HarshKapadia2** [comment]
Two more things to be done, @MahmoudDawood
- Change the example to `git commit --allow-empty -m "<commit_message>"`
- Use interactive rebasing to squash all your commits into one commit with the commit message '`:truck: update: Add` &#96;--allow-empty&#96; `option (#85)`' and force push to your branch. LMK if you don't understand that.

**Comment by HarshKapadia2** [comment]
Any updates, @MahmoudDawood? Please LMK if you're having any issues.

**Comment by MahmoudDawood** [comment]
Sorry for the late reply, today was my free day xD
I'll be back tomorrow on it if it's ok with you.
Thanks for your reminder Harsh!

**Comment by HarshKapadia2** [comment]
Sure, no issues.

**Comment by MahmoudDawood** [comment]
@HarshKapadia2 
I had issues with git couldn't squash past commits so I've made a new clean pull request to be merged with all changes added.
Sorry for the mess, it's my first issue.

**Comment by HarshKapadia2** [comment]
LGTM. I rebased the commits.

Thank you for the contribution, @MahmoudDawood!

**Comment by MahmoudDawood** [comment]
@HarshKapadia2  Woow! Thanks for your support bro <3

**Pull request merged**
