### PR TITLE
Add resources, Issue #58

### PR DESCRIPTION
**Pull request by crmsnbleyd**
-Created new sub-heading ```Browser extensions for GitHub```
    * Added link to GitZip
    * Added link to Refined Github
-Added <https://try.github.io> under subheading ```Git Documentation```

### CODE REVIEW

**Comment by HarshKapadia2** [comment]
Thank you for the PR, @crmsnbleyd!

I realised after your PR that I didn't mention the exact details that I needed for the link text. I have described the changes that I need below. Sorry for the inconvenience!

A few changes:
- Please rename 'Github' to 'GitHub'.
- For https://try.github.io, let the link text be `<link>[GitHub's resources for Git^]`
- For the browser extensions sub-heading
	- https://github.com/sindresorhus/refined-github#install[Refined GitHub^] - Simplifies the GitHub interface and adds useful features (available for Chrome, Edge, Firefox and Opera)
	- https://gitzip.org/#extension[GitZip for GitHub^] - Only download required sub-folders/files from GitHub repos (available for Chrome, Edge and Firefox)

**Comment by crmsnbleyd** [comment]
@HarshKapadia2 I have made another commit making the changes requested, please review it.

**Comment by HarshKapadia2** [comment]
Ah you forgot to change the links for the browser extensions...
Also, please keep your commit messages short and add the descriptive stuff to the commit description if you need.

**Comment by crmsnbleyd** [comment]
Updated the links!

**Comment by HarshKapadia2** [comment]
Looks fine to me.
Thank you for the PR, @crmsnbleyd!
All the best for your open source journey!

**Pull request merged**
