### PR TITLE
Add notice regarding main and master (#47)

### LINKED ISSUE #47: replace master by main.
Since from now on all repositories have default branch main, I think either all `master`s on the website should be replaced by `main`, or a notification on top of the page could be given for now.

### PR DESCRIPTION
**Pull request by tusharnankani**
- Fixes #47 
- Added the Admonition - NOTE regarding main and master. 
  - Let me know if something is to be changed.
- Fixed minor typo (requirememnts -> requirements) and README errors.

### CODE REVIEW

**Comment by HarshKapadia2** [comment]
Thank you for the PR!

> Fixed minor typo (requirememnts -> requirements) and README errors.

Thank you for these extra changes, but in the future please open a new PR for such changes.

Coming to the `NOTE`:
- I think the note should be placed just below the last note (on 'Git terms') in the 'Prefece' section.



- The language of the note is not the same as the entire web site.
	- Pronouns are either not included at all or third person pronouns like 'they' and 'one' are used.
- Please generate an `index.html` file using Asciidoctor as instructed in the [`CONTRIBUTING.md`](https://github.com/HarshKapadia2/git_basics/blob/master/CONTRIBUTING.md) file.

**Comment by tusharnankani** [comment]
> Thank you for these extra changes, but in the future please open a new PR for such changes.

My bad! 
Fixed the commits, created a different PR 👍🏻 

> - The language of the note is not the same as the entire web site.
>   - Pronouns are either not included at all or third-person pronouns like 'they' and 'one' are used.
>   - Please generate an index.html file using Asciidoctor as instructed in the CONTRIBUTING.md file.

Done 👍🏻

**Comment by tusharnankani** [comment]
> - I think the note should be placed just below the last note (on 'Git terms') in the 'Preface' section.

Fixed 👍🏻

**Comment by HarshKapadia2** [comment]
> Thank you for these extra changes, but in the future please open a new PR for such changes.

The changes were supposed to be made in future PRs, not for this PR.

Now to keep the commit history of the repo clean and straightforward, please open a new PR for issue #47.

Also, do view the `CONTRIBUTING.md` file again, as it has been modified.

**Comment by tusharnankani** [comment]
> Now to keep the commit history of the repo clean and straightforward, please open a new PR for issue #47. Please add a reference to this PR in the new PR's comments.

Done via #57

**Pull request closed without merging**
