### PR TITLE
External link in new tab (#28)

### PR DESCRIPTION
**Pull request by Rodrigue819**

### CODE REVIEW

**Comment by Rodrigue819** [comment]
Must merge the 2 PR on task #23 before this one. Sorry about posting them in the wrong order.

**Comment by HarshKapadia2** [comment]
> Must merge the 2 PR on task #23 before this one. Sorry about posting them in the wrong order.

No problem, it happens. Thank you for the PRs!

**Comment by HarshKapadia2** [comment]
Could you keep the original text for this link in `git_bash.adoc`? (Add `[role=external,window=_blank]` to it though.)
image

**Comment by HarshKapadia2** [comment]
Also, I just realised that you have not made the changes mentioned in issues #23 and #28 for `index.adoc`.
Please make a separate commit for this (with the commit message referencing both issues) in this PR after you finish with the `git_bash.adoc` commit as mentioned in the above comment. Remember to generate the `index.html` file again.

**Comment by HarshKapadia2** [comment]
Why did you close the PR, @Rodrigue819!? You just have a few more changes to make!

**Comment by Rodrigue819** [comment]
It's just the time I do the ajustments. Don't worry I'll reopen it shortly.
________________________________

**Comment by HarshKapadia2** [comment]
You should keep a PR open while you work on it. Closing a PR implies that you aren't going to be working on it anymore. Do remember that in the future!

**Comment by Rodrigue819** [comment]
I'm done with the index. There's only that "these" i'm not sure if I should fix.
image
I don't really know how I could change the phrase to remove "these" if I need to. I thought about simply removing these and put the link on "Git terms" but i'm not sure how it sounds.

**Comment by HarshKapadia2** [comment]
One might want to familiarize themselves with some [Git Terms] before starting...
Does that work?

**Comment by HarshKapadia2** [comment]
Just reminding you that the following change in this PR is pending as well: https://github.com/HarshKapadia2/git_basics/pull/48#issuecomment-706381662

**Comment by Rodrigue819** [comment]
Did the change in index.adoc. The change in #48 was done in commit a2bb662.
Hope everything is ok now!

**Comment by HarshKapadia2** [comment]
My bad! I didn't see that!
Things seem fine.

Thank you for all the PRs, @Rodrigue819!

By the way, I am conducting a session on Hacktoberfest and Open Source tomorrow (Oct 11) at 3PM IST. You can register and view the details at https://bit.ly/otcHacktoberfest1 if you're interested.

**Comment by KartikSoneji** [comment]
@Rodrigue819 GitHub has an excellent feature of being able to mark a PR as `draft`.
Marking a PR as draft is a good way to signify that it is not ready yet, but you are working on it.

[Docs about draft Pull Requests](https://docs.github.com/en/free-pro-team@latest/github/collaborating-with-issues-and-pull-requests/about-pull-requests#draft-pull-requests)

**Comment by Rodrigue819** [comment]
Thanks for that cue. Will use it!!

Get Outlook for Android<https://aka.ms/ghei36>
________________________________

**Pull request merged**
