### PR TITLE
Issue #66 - Correcting alt attributes

### PR DESCRIPTION
**Pull request by mtwn105**
Fixed all the `alt` attributes, I could find in the asciidocs.

### CODE REVIEW

**Comment by HarshKapadia2** [comment]
Thank you for your PR, @mtwn105!

For most of the changes, you have taken up the pattern of `image::file_name.ext[file name, size_1, size_2]`, so please change the ones with `alt="file name"` to that format to keep things uniform.

**Comment by mtwn105** [comment]
Okay @HarshKapadia2, I will make those changes and update you.

**Comment by mtwn105** [comment]
Hi @HarshKapadia2 

Please review my changes to make it consistent.

**Comment by HarshKapadia2** [comment]
You misread what I wrote and made the exact opposite change, @mtwn105. 😂 
It's okay though, I appreciate your help! 😃

**Pull request merged**
